services:
  - type: web
    name: Arbitraje_Taekwondo
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    env: node
    envVars:
      - key: NODE_ENV
        value: production
